[tool.pyright]
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
# typeCheckingMode = "strict"
strict = [
    "**/lab7", "**/hw7",
    "**/lab8", "**/hw8",
    "**/lab9", "**/hw9",
    "**/lab10", "**/hw10",
    "**/lab11", "**/hw11",
]
reportUnusedImport = false

[tool.ruff]
select = [
    "E", "F", "W", "I", 
    "C90", "N", "D", "UP", 
    "YTT", "ANN", "S", "FBT", 
    "B", "A", "C4", "DTZ",
    "ISC", "ICN", 
    "PIE", "PYI", "RSE", "RET", "SIM",
    "TCH", "PTH", "PL", "RUF"
]
ignore = ["W293", "D1", "ANN101", "S101", "W191", "PTH123", "PLR2004"]
